name: "Setup complyctl environment"
description: "Setup environment for complyctl running"

inputs:
  product:
    description: "The chosen product"
    required: true
  catalog:
    description: "OSCAL content catalog of the chosen product"
    required: true
  profile:
    description: "OSCAL content profile of the chosen product"
    required: true

runs:
  using: composite
  steps:
    # Install dependency on fedora
    - name: Install dependency
      run: dnf install wget make scap-security-guide git jq gh -y
      shell: bash

    # Configure Git for safe directory
    - name: Configure Git for safe directory
      run: git config --global --add safe.directory /__w/complyctl/complyctl
      shell: bash

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version-file: './go.mod'

    # Build complyctl and setup complyctl
    - name: Build complyctl and setup complyctl
      run: sh tests/build_init_env.sh ${{ inputs.product }} ${{ inputs.catalog }} ${{ inputs.profile }}
      shell: bash
